Repository kookmin-sw/capstone-2020-6, pull requests merged in 2020-05, with the labels that each got.

#106 feat: Implement CAPTCHA v0
  src/web-frontend/src/Router.tsx
  src/web-frontend/src/pages/PageCaptcha.css
  src/web-frontend/src/pages/PageCaptcha.tsx
Labels: FE, enhancement

#117 fix: Fix z-index error in navbar
  src/web-frontend/src/components/Navigation.css
Labels: FE, bug

#131 Web frontend finishpage
  src/web-frontend/src/Router.tsx
  src/web-frontend/src/components/Avatar.css
  src/web-frontend/src/components/Avatar.tsx
  src/web-frontend/src/components/LabelingFinishButton.tsx
  src/web-frontend/src/components/LabelingNextBtn.css
  src/web-frontend/src/components/LabelingNextBtn.tsx
  src/web-frontend/src/components/MyPageCard.css
  src/web-frontend/src/components/MypageCard.tsx
  src/web-frontend/src/pages/PageCaptcha.css
  src/web-frontend/src/pages/PageCaptcha.tsx
  src/web-frontend/src/pages/PageLabelingFinish.tsx
  src/web-frontend/src/pages/PageLabelingRegister.tsx
  src/web-frontend/src/pages/PageLabelingResult.css
  src/web-frontend/src/pages/PageMypagePW.css
Labels: FE, enhancement

#156 Web frontend view all project
  src/web-frontend/src/Router.tsx
  src/web-frontend/src/pages/PageMain.css
  src/web-frontend/src/pages/PageMain.tsx
  src/web-frontend/src/pages/PageViewAllProjects.css
  src/web-frontend/src/pages/PageViewAllProjects.tsx
  src/web-frontend/src/stores/PageViewAllProjectsStore.ts
  src/web-frontend/src/stores/index.ts
Labels: FE, enhancement

#162 feat: Project List Component V1
  src/web-frontend/src/components/ProjectListTable.tsx
  src/web-frontend/src/pages/PageViewAllProjects.tsx
Labels: FE, enhancement, question

#164 Implement loading components
  src/web-frontend/src/components/Loading.tsx
Labels: FE, enhancement

#168 refactor: Delete useless UI in register
  src/web-frontend/src/pages/PageRegister.tsx
Labels: FE

#187 Web frontend imagecapture
  src/web-frontend/src/pages/PageLabelingImageCapture.css
  src/web-frontend/src/pages/PageLabelingImageCapture.tsx
Labels: FE, enhancement

#204 feat: Modify labelingType url
  src/web-frontend/src/Router.tsx
  src/web-frontend/src/pages/PageLabeling.tsx
  src/web-frontend/src/stores/LabelingPageStore.ts
Labels: FE

#208 Web frontend Main page
  src/web-frontend/src/pages/PageLabeling.tsx
  src/web-frontend/src/pages/PageLabelingRegister.tsx
  src/web-frontend/src/pages/PageMain.tsx
  src/web-frontend/src/pages/PageMypageProject.tsx
  src/web-frontend/src/pages/PageViewAllProjects.tsx
  src/web-frontend/src/pages/PageViewAllProjectsFinished.tsx
  src/web-frontend/src/stores/LabelingPageStore.ts
  src/web-frontend/src/stores/ProjectListStore.ts
Labels: FE, bug, enhancement

#218 Web frontend progress bar
  src/web-frontend/src/components/CardProject.tsx
  src/web-frontend/src/components/ProgressBar.tsx
Labels: FE

#231 feat: Implement Text Select By Image
  src/web-frontend/src/Router.tsx
  src/web-frontend/src/pages/PageLabelingTextSelectByImage.css
  src/web-frontend/src/pages/PageLabelingTextSelectByImage.tsx
  src/web-frontend/src/stores/LabelingTextSelectByImageStore.ts
Labels: FE, enhancement

#236 feat: Add project status manage buttons
  src/web-frontend/src/pages/PageLabelingResult.css
  src/web-frontend/src/pages/PageLabelingResult.tsx
  src/web-frontend/src/pages/PageMypageProject.tsx
  src/web-frontend/src/stores/LabelingResultStore.ts
  src/web-frontend/src/stores/MyPageProjectStore.ts
Labels: FE, enhancement
